import { NextResponse } from "next/server";
import dbConnect from "@/lib/mongodb";
import { StockTransaction } from "@/models/Inventory";

export async function GET() {
  try {
    await dbConnect();
    const transactions = await StockTransaction.find({}).sort({ createdAt: -1 });
    return NextResponse.json(transactions);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    await dbConnect();
    const body = await request.json();
    delete body._id;
    
    // Protect against old invalid batchIds generated by the frontend
    if (body.batchId && !/^[a-fA-F0-9]{24}$/.test(body.batchId)) {
      delete body.batchId;
    }

    // Use upsert to avoid duplicate entries when array is sent repeatedly
    const transaction = await StockTransaction.findOneAndUpdate(
      { transactionNumber: body.transactionNumber },
      body,
      { upsert: true, new: true }
    );
    return NextResponse.json(transaction, { status: 201 });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
